connection aws-bridge
address aa0ttgw7natni-ats.iot.eu-north-1.amazonaws.com:8883

# Bridge all 'prodino' topics to AWS
topic prodino/# out 1 "" ""

# Connection Settings
start_type automatic
cleansession true
notifications false

# AWS requires MQTT v3.1.1
bridge_protocol_version mqttv311

# Security (Mutual TLS)
bridge_cafile /etc/mosquitto/certs/root-ca.pem
bridge_certfile /etc/mosquitto/certs/rutx12-cert.pem.crt
bridge_keyfile /etc/mosquitto/certs/rutx12-private.pem.key

# Logs
log_type all
