#!/usr/bin/env python3
"""Regenerate firmware/src/aws_certs_store.h from the device PEM files.

The output header is GITIGNORED (it embeds the AWS device private key) and is
served to the in-HLC gateway by the firmware's get_aws_certs endpoint.
See docs/AWS_CERTS_STORE.md for the full picture.

Run from anywhere; paths are resolved relative to the repo root:

    python3 tools/generate_aws_certs_store.py

Inputs (all gitignored, obtained out-of-band — never via git):
    GRK_Board_Direct_keys/*-certificate.pem.crt   device certificate
    GRK_Board_Direct_keys/*-private.pem.key       device private key
    server/web_ui/certs/AmazonRootCA1.pem         Amazon Root CA 1 (public)
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
KEYS_DIR = REPO_ROOT / "GRK_Board_Direct_keys"
ROOT_CA = REPO_ROOT / "server/web_ui/certs/AmazonRootCA1.pem"
OUTPUT = REPO_ROOT / "firmware/src/aws_certs_store.h"

AWS_ENDPOINT = "a21aufrn5hgzfe-ats.iot.eu-north-1.amazonaws.com"
AWS_PORT = 8883


def find_one(pattern: str) -> Path:
    matches = sorted(KEYS_DIR.glob(pattern))
    if len(matches) != 1:
        sys.exit(
            f"error: expected exactly one {pattern} in {KEYS_DIR}, "
            f"found {len(matches)}: {[m.name for m in matches]}"
        )
    return matches[0]


def c_lines(path: Path) -> str:
    """Render a PEM file as C string-literal continuation lines."""
    text = path.read_text().strip()
    if "-----BEGIN" not in text:
        sys.exit(f"error: {path} does not look like a PEM file")
    lines = text.splitlines()
    return "\n".join(f'"{line}\\n" \\' for line in lines).rstrip(" \\") + ";"


def main() -> None:
    cert_path = find_one("*-certificate.pem.crt")
    key_path = find_one("*-private.pem.key")
    if not ROOT_CA.exists():
        sys.exit(f"error: root CA not found at {ROOT_CA}")

    OUTPUT.write_text(f"""\
// AWS IoT device credentials for thing "GRK_Board_Direct" (SN2003 board).
// GITIGNORED - contains the device PRIVATE KEY. NEVER COMMIT.
// Served to the in-HLC gateway via the get_aws_certs endpoint (http_server.cpp).
// Generated by tools/generate_aws_certs_store.py - see docs/AWS_CERTS_STORE.md.
#ifndef AWS_CERTS_STORE_H
#define AWS_CERTS_STORE_H

// AWS IoT Core ATS endpoint (account a21aufrn5hgzfe, region eu-north-1)
#define AWS_ENDPOINT "{AWS_ENDPOINT}"
#define AWS_PORT {AWS_PORT}

// Device certificate (RSA, CN="AWS IoT Certificate", expires 2049-12-31)
const char AWS_DEV_CERT[] =
{c_lines(cert_path)}

// Device private key (RSA 2048) - lives ONLY here, on the board, and in AWS
const char AWS_DEV_KEY[] =
{c_lines(key_path)}

// Amazon Root CA 1 (public, from https://www.amazontrust.com/repository/AmazonRootCA1.pem)
const char AWS_ROOT_CA[] =
{c_lines(ROOT_CA)}

#endif // AWS_CERTS_STORE_H
""")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  cert: {cert_path.name}")
    print(f"  key:  {key_path.name}")


if __name__ == "__main__":
    main()
